### ISSUE TITLE
Fix Player's colour

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#109]
When people die they are still pepto bismol pink and when they are alive they are assigned a random colour. When the person dies either make them a lighter grey or make them semi transparent using a tint like this: tint(255, 255, 255, 125)   (The last value is the alpha out of 255 so this would give the user 50% visibility)

**Comment by iryanclarke** [comment]
Estimate: 1 hours
Actual: 0.5 hours
Comments:
