### ISSUE TITLE
Have green baby balloon for yellow + blue balloon collision

### ISSUE THREAD

**Issue by iryanclarke** [screaming-goat/the-game#110]
Right now there is only yellow + blue baby balloons, but if yellow and blue combine it needs to make a green one

**Comment by kieralundberg** [comment]
There are green baby balloons. Please check the work completed last week

**Comment by iryanclarke** [comment]
Ah it was? My bad, I was just going off the stuff I saw in the baby balloon colour detection/ etc

**Comment by teganscott** [comment]
This is not an enhancement, this is something that was written in our design document.

**Comment by teganscott** [comment]
Duplicate of task #83
Estimated Time: N/A
Actual Time: N/A
