### ISSUE TITLE
Code: Combining balloon shapes on balloon balloon collision

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#21]
When two balloons collide of different shapes, have the resulting baby balloon be a combination of their two shapes

**Comment by iryanclarke** [comment]
Will need to discuss if this works, as convex Box2D shapes don't like collisions...
estimated: 7 hours
actual: 1 (theorycrafting)
comments: moved to next sprint (6)

**Comment by iryanclarke** [comment]
Moved to Milestone7

**Comment by iryanclarke** [comment]
estimated: 15 hours
actual: 1 (so far)
comments:

**Comment by teganscott** [comment]
Task no longer exists
