### ISSUE TITLE
Code: Particle Generation for birds

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#22]
Particle generation for flock of birds.

**Comment by iryanclarke** [comment]
Blocker #2 and #12

**Comment by iryanclarke** [comment]
estimated: 8 hours
actual: 8~ hours
comments: flocking is mostly complete, merely need assets/animation for bird

**Comment by iryanclarke** [comment]
Will be moved to Milestone 5, but placeholder for Anthony to see
