### ISSUE TITLE
Kinect: Balloons represented by their actual colour

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#23]
Each physical balloon has it's own colour. Have the silhouettes of the balloons on the screen be represented by this colour.

**Comment by iryanclarke** [comment]
estimated: 5 hours
actual: 2 (thus far)
comments: moved to next sprint (5)

**Comment by iryanclarke** [comment]
estimated: 5 hours
actual: 6 
comments: still a little buggy but working
