### ISSUE TITLE
Test: Using projector to project on wall

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#33]
This will have to be done throughout the development process. This is here as a reminder to be done before Beta.

**Comment by teganscott** [comment]
This will be done in class on Wednesday

**Comment by teganscott** [comment]
Estimated Time: 4 hours
Kiera will be getting sheet to project onto, we have a projector borrowed for 10 days beginning on  Tuesday.

**Comment by kieralundberg** [comment]
actual: 0.5 hours
