### ISSUE TITLE
Test: Insure there are no major bugs for Beta

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#38]
General testing to insure there are no major flaws or bugs for beta

**Comment by iryanclarke** [comment]
estimated: 10 hours
actual: 
comments: blocker on combining all tasks and other's tasks

**Comment by iryanclarke** [comment]
estimated: 10 hours
actual: 20 hours
comments: Noise in kinect detection made moving Box2D element sticking difficult to balloon
