### ISSUE TITLE
Lightning Strike

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#60]
Code in dark clouds generation with lightning strike

**Comment by teganscott** [comment]
Estimated Time: 4 hours

**Comment by kieralundberg** [comment]
new estimate: 6 hours
comments: have spent 3 hours on it already, still have to get lightning animation working and figure out box2d

**Comment by teganscott** [comment]
Re-assigned to Tegan and moved to Milestone 8.5

**Comment by teganscott** [comment]
Estimated Time: 5 hours

**Comment by teganscott** [comment]
Actual Time: 7 hours
Using an attract to force the box2D object to move
