### ISSUE TITLE
Tree enemy collision

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#61]
Find the vertex points of the tree to create a box2D element based on it. Using physics engine you should be able to find the shape edges more easily. When the balloon collides with the tree, the balloon should pop or give some kind of warning that it has been hurt.

**Comment by teganscott** [comment]
Estimated Time: 5 hours

**Comment by teganscott** [comment]
Turn tree into box2D shape.

**Comment by iryanclarke** [comment]
estimated: 5 hours
actual: 2 hours (so far)
comments: this is moved to next sprint as the tree in the mountain scene needs to be done as well

**Comment by teganscott** [comment]
Complete for Saturday before we meet.

**Comment by iryanclarke** [comment]
Estimate: 5 hours
Actual: 3
Comments: Added in tree objects to mountain scene
