### ISSUE TITLE
Mountain Assets

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#65]
Develop more mountain assets to let the scene look more filled.

**Comment by kieralundberg** [comment]
estimated: 2
actual:
comments:

**Comment by kieralundberg** [comment]
mike: come up with three concepts for possible items to be added to scene (foreground or midground preferred) in illustrator 
note: if planning on animating, keep joints in mind

**Comment by mikez771** [comment]
actual hours: 2
comments: Mountain goat, cabin and rocks created as assets.
