### ISSUE TITLE
Farm Assets

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#66]
Develop more farm assets to make the farm scene seem more filled

**Comment by kieralundberg** [comment]
estimated: 1
actual:
comments:

**Comment by kieralundberg** [comment]
mike: come up with concept for three possible elements to be added to scene

**Comment by kieralundberg** [comment]
mike: come up with three concepts for possible items to be added to scene (foreground or midground preferred) in illustrator 
note: if planning on animating, keep joints in mind

**Comment by mikez771** [comment]
actual: 1 hour
comments: Hay bale, Hay Pile, Pitchfork created as assets.
