### ISSUE TITLE
Fix background transition bug

### ISSUE THREAD

**Issue by iryanclarke** [screaming-goat/the-game#71]
Fix the bug where no environment shows up after the first scene is shown.

**Comment by teganscott** [comment]
Estimated Time: 5 hours

**Comment by teganscott** [comment]
Spent 18 hours trying to get Kinect to work with my machine. Was not able to get to this task.

**Comment by iryanclarke** [comment]
Moved to Milestone 8

**Comment by teganscott** [comment]
Actual Time: 2 hours
