### ISSUE TITLE
Connect parameters to buttons

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#90]
All of the customize-able parameters to calibrate the system should be set to keys on the keyboard. This should include the Kinect settings, number of contours for a skeleton/balloon, and whatever else you feel is necessary.

**Comment by teganscott** [comment]
Estimated Time: 2 hour
- Kinect parameters 
- Lightning bolt (will need to wait until lighting is coded)
- Bandit appear
- Change theme
- Balloon generator
- Baby balloon generator
- New bird appears on screen

**Comment by teganscott** [comment]
Tegan is doing lightning bolt and change theme

**Comment by iryanclarke** [comment]
Baby balloon is done, same with Kinect stuff

**Comment by iryanclarke** [comment]
Estimate: 1 hours
Actual: 1 hour
Comments:
