### ISSUE TITLE
Balloon is solid colour

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#91]
The balloon no longer flashes colours. In one of the milestones Kiera coded a small threshold for blue and yellow. Use that to determine the colour of the balloon.

Estimated Time: 3 hours

**Comment by teganscott** [comment]
Complete for Saturday before we meet.

**Comment by iryanclarke** [comment]
Estimate: 3 hours
Actual: 4 hours
Comments: Was very tricky at first, but was completed
