### ISSUE TITLE
Multiple people and balloons

### ISSUE THREAD

**Issue by teganscott** [screaming-goat/the-game#92]
- track last known position of balloon to associate with the contour number
- Found this issue in class on Wednesday

Estimated Time: 6 hours

**Comment by teganscott** [comment]
We will work on this together on Saturday (Ian and Tegan)

**Comment by iryanclarke** [comment]
Estimate: 6 hours
Actual: 7 hours
Comments: Moving to more OOP caused alot of bugs at first but is much more solid for ballon tracking/user alive states
